# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "comphass-infra-terraform-state-backend"
    dynamodb_table = "terraform-state-lock-table"
    encrypt        = true
    key            = "lab/transport-api/security_groups/alb_sg/terraform.tfstate"
    region         = "us-east-1"
  }
}
